name: 🐞 Bug Report
description: Report a bug or issue with the Vega app
labels: [bug]
body:

    - type: textarea
      id: summary
      attributes:
          label: Brief summary
          description: Please describe, what went wrong
      validations:
          required: true

    - type: textarea
      id: reproduce-steps
      attributes:
          label: Steps to reproduce
          description: Please provide a way to reproduce this issue. Screenshots or videos can be very helpful
          placeholder: |
              Example:
                1. First step
                2. Second step
                3. Issue here
      validations:
          required: false


    - type: input
      id: vega-version
      attributes:
          label: Vega version
          description: Specify the version of the app you are using.
          placeholder: |
              Example: "1.0"
      validations:
          required: true

    - type: checkboxes
      id: acknowledgements
      attributes:
          label: Acknowledgements
          options:
              - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
                required: true
